### ISSUE TITLE
Preliminary features/feedback

### ISSUE THREAD

**Issue by pr4deepr** [clij/clijx-assistant#14]
Hi Robert
  Great plugin. I've been enjoying using this a lot.

In terms of features I would like to see added:
* Canny edge detection, just like 3D Edge and Symmetry filter in 3D ImageJ suite (not sure if you already have this?). 
* Marker controlled watershed from MorpholibJ
If I am using CLIJx to generate seeds (labelling) and binary images (mask), then if I have edges image I can use these images for segmenting cells using Marker Controlled Watershed.
* Grey-level attribute filtering. 

Some preliminary feedback:
* When using the CLIJx-assistant, I can get a bit lost with the sequence of windows especially with long workflows. Is it possible to have an auto arrange of some sorts where it arranges the windows in sequence of the operations performed??
* To differentiate between ImageJ windows and CLIJx-assistant windows, is it possible for the CLIJx-assistant managed windows to have a coloured outline of some sorts?? If this is a good idea, then perhaps colour can change based on which CLIJx window is currently active Green for active and red for inactive? This may not help colour-blind people though (skyblue instead of red then). 
* Also, the same way you can generate a macro based on the workflows, is it possible to do the opposite? As in, use a macro to generate the CLIJx-assistant workflow which I can tweak, maybe add or delete components and regenerate a macro/script?

I ran CLIJ2_clear() a few times by mistake in a macro the same time CLIJx-assistant is active (I know I'm multitasking) . This has caused clijx-assistant to become inactive as the GPU memory has been wiped. This is purely from a user perspective, but is it possible to control for this??

Let me know if you already have any of these features or if there is any other way of doing the above.

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr ,

thanks for the feedback! I split it into several issues. This should make it easier to discuss things and potential implementations.

https://github.com/clij/clijx/issues/16
https://github.com/clij/clijx/issues/17

https://github.com/clij/assistant/issues/15
https://github.com/clij/assistant/issues/16
https://github.com/clij/assistant/issues/17
https://github.com/clij/assistant/issues/18

Thanks again for the feedback!

Cheers,
Robert
