### ISSUE TITLE
Auto-arrange windows

### ISSUE THREAD

**Issue by haesleinhuepf** [clij/clijx-assistant#15]
Suggested by @pr4deepr

'''
When using the CLIJx-assistant, I can get a bit lost with the sequence of windows especially with long workflows. Is it possible to have an auto arrange of some sorts where it arranges the windows in sequence of the operations performed??
'''

See also:
https://github.com/clij/assistant/issues/14

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr,

if you turn off Auto-Positioning (in the right click menu) and click on the main menu Window > Tile, it looks like this:
![image](https://user-images.githubusercontent.com/12660498/94183896-6ec8d000-fea3-11ea-9d06-ead9401f2ecf.png)

Does that make sense or would you arrange the windows differently?

I could make a short-cut doing this in the right-click menu...

**Comment by pr4deepr** [comment]
Yea, this works quite well. As far as I can tell, it arranges it in the order of operations!
The only other issue would be making sure the dialog box for each window is active and comes in front when clicking the corresponding windows. 
I think a shortcut would be great!

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr ,

I worked a bit on automatic default-positions of windows:

![window_positioning](https://user-images.githubusercontent.com/12660498/94657178-58869e00-0301-11eb-8918-3c879eb84265.gif)

The new scheme is available via the update site. Feel free to give it a try and let me know what you think!

Cheers,
Robert
