### ISSUE TITLE
Visual differentiation of assistant-windows from ImageJ-windows

### ISSUE THREAD

**Issue by haesleinhuepf** [clij/clijx-assistant#16]
Suggested by @pr4deepr

'''
To differentiate between ImageJ windows and CLIJx-assistant windows, is it possible for the CLIJx-assistant managed windows to have a coloured outline of some sorts?? If this is a good idea, then perhaps colour can change based on which CLIJx window is currently active Green for active and red for inactive? This may not help colour-blind people though (skyblue instead of red then).
'''

See also:
https://github.com/clij/assistant/issues/14

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr,

with https://github.com/clij/assistant/commit/d4eb0aeace4f5410c73eaf3af113b07497e1552d windows share their color with the "Refresh" button:
![image](https://user-images.githubusercontent.com/12660498/94183592-f104c480-fea2-11ea-87b6-4c0143245d5c.png)

What do you think about that solution?

Thanks!

Cheers,
Robert

**Comment by pr4deepr** [comment]
oooo, I love the idea of sharing the colour with the refresh button. 
The windows have a colour to make them distinct and the colours have a purpose!
You can see which windows have completed processing without looking at the refresh button. 
BTW, what does the yellow colour mean?

**Comment by haesleinhuepf** [comment]
Awesome. Devs and users have the best ideas together ,😉

red=not started
yellow=computing
green=done

**Comment by pr4deepr** [comment]
:)
I thought so, but on occasion I see the red colour on for a bit, especially with median filters...

**Comment by haesleinhuepf** [comment]
Alright. I close this issue then. 11 more to go :-)

Thanks again for the feedback. It's a pleasure working with you!
