### ISSUE TITLE
clij assistant_suggestions

### ISSUE THREAD

**Issue by pr4deepr** [clij/clijx-assistant#41]
Hi Robert
   For the option of adding custom suggestions from a folder of CLIJ2 macros, could you modify it so it parses through the whole directory structure in a folder, i.e., nested folders?
I tried it on a folder of different macros which I have arranged based on my projects, and the suggestions file only shows a graph based on just a couple of macros that are in the main folder and not in sub folders.

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr ,

the usage miner now supports that. Would you mind testing [it? (download here)](https://github.com/clij/usage-miner)

If it works, I enable the same features in clij-assistant.

Thanks for the suggestion!

Cheers,
Robert

**Comment by pr4deepr** [comment]
Done!
