### ISSUE TITLE
area fraction; label and binary image

### ISSUE THREAD

**Issue by pr4deepr** [clij/clijx-assistant#47]
Hi Robert
    Hope you are well. A question, is it possible to measure the area fraction using a label image and binary image? If so, can this be used in the Label Processing/Measurement option to get a label image with the labels having the values for the area fraction (or a custom parameter)?

Happy Holidays.

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
Hey Pradeep @pr4deepr ,

great question. The solution is maybe not obvious, but yes you can do this. As the pixels in the binary image are 0 and 1, you can measure the area fraction by measuring the mean intensity within the labels. For quantiative analysis, you should use [statisticsOfLabelledPixels](https://clij.github.io/clij2-docs/reference_statisticsOfLabelledPixels). For visualisation, you can use [Label Mean Intensity Map](https://clij.github.io/clij2-docs/reference_labelMeanIntensityMap):

![image](https://user-images.githubusercontent.com/12660498/103100889-1b3a5f80-4615-11eb-8db0-981b828168a8.png)

Here you also find the corresponding IDFG groovy file for loading my workflow:
[partial_overlap_quantification_IDFG.zip](https://github.com/clij/assistant/files/5740235/partial_overlap_quantification_IDFG.zip)

Let me know if this does the intended job!

Happy Holidays!

Cheers,
Robert

**Comment by pr4deepr** [comment]
Thanks for the response and apologies for the delay. 
It definitely does the intended job and I agree its not immediately obvious. 
Is it worth adding the name area fraction in the name or maybe when searching for area fraction in macro or search bar that this option comes up?

**Comment by haesleinhuepf** [comment]
Oh, that's actually a great idea. You mean new function like this?

```
excludeLabelsWithOverlapBelowAreaFraction(label_map1, label_map2, label_map_destination, area_fraction);
```

**Comment by pr4deepr** [comment]
Yup, like this.. 
The blob image example is a really nice one..

Also, is the  statisticsOfLabelledPixels available on clij assistant menu?? I couldn't find it..

**Comment by haesleinhuepf** [comment]
> Also, is the statisticsOfLabelledPixels available on clij assistant menu?? I couldn't find it..

No, it's not, because it doesn't result in an image ;-) I don't know yet how to make it available in the assitant...

**Comment by pr4deepr** [comment]
Ahh, ok. Thanks for letting me know!
