### ISSUE TITLE
Reloadable Groovy workflow; choose image option

### ISSUE THREAD

**Issue by pr4deepr** [clij/clijx-assistant#48]
Hi @haesleinhuepf 
     When exporting the workflow as a 'reloadable groovy script',  the path of the image used is hardcoded into the workflow. This becomes an issue when I'd like to share this with someone. 
Could you add an option for choosing the image, like a dialog?

Currently, this is the workflow:
```
// Load image from disc 
image1 = net.haesleinhuepf.clijx.assistant.utilities.AssistantUtilities.openImage("**image-path**");
```

Instead, can you add an option like this as well? I've used script parameters here.

```
#@ File (label = "Choose Image", style="open") filename
filename =filename.toString();
filename = net.haesleinhuepf.clijx.assistant.utilities.AssistantUtilities.openImage(filename);
```

This has been working for me.  Perhaps adding it as a comment and giving the user the option for commenting it out may help?
If you are ok with it, I'm assuming it should be added [here](https://github.com/clij/assistant/blob/625db3067b25a6c98d7a77631372506230427456/src/main/java/net/haesleinhuepf/clijx/assistant/scriptgenerator/AssistantGroovyGenerator.java#L28)?

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr,
 
> This becomes an issue when I'd like to share this with someone.

In practice actually not, because if you run the script and the mentioned file is not found, the CLIJ-assistant will open a dialog and ask the user for the location of the image.

I'm happy to implement the suggested change, but before doing so, try it out and let me know if the current implementation does the job.

Thanks!

Cheers,
Robert

**Comment by pr4deepr** [comment]
Hey @haesleinhuepf 
   Yes, you are right. I tried this a while ago and I was having issues.
Should have tried it again before opening this issue. 
Apologies.

Thanks for the response.

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
No worries :-)
And thanks for testing again!
