### ISSUE TITLE
Sum projection

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#49]
When doing a sum projection it can happen that the current data type overflows.
Could be nice to print a warning if that happens (for inexperienced users).
In fact, in ImageJ it will always output a sum projection as floating point to avoid this, but I am not sure if that's the best solution.

**Comment by haesleinhuepf** [comment]
Hey @tischi,

that's a bug! Thanks for reporting. I will enter 32-bit Float as default output-type [here](https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/plugins/SumZProjection.java#L60) and also check the other projections.

Cheers,
Robert
