### ISSUE TITLE
Segmentation feature measurements

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#51]
Is there already something to, e.g., extract shape feature measurements?
I could not find it... or should I use, e.g., MorpholibJ for this last step?

**Comment by haesleinhuepf** [comment]
Hi @tischi ,

yes, there is a hand full of measurements available. First of all, from the assistant, you might want to explore the label extension /ratio maps:
![image](https://user-images.githubusercontent.com/12660498/112718054-d9a9a100-8ef0-11eb-9105-ab4ec92cc2e9.png)

In macro, you can access corresponding measurements via [statistics of labeled pixels](https://clij.github.io/clij2-docs/reference_statisticsOfLabelledPixels). There, take a look at the columns "MAX_DISTANCE_TO_MASS_CENTER", "MAX_DISTANCE_TO_MASS_CENTER_RATIO" etc. These measurements are a bit unusual compated to MorphoLibJ and plain ImageJ, but they can efficiently be computed in parallel ;-)

Let me know if this helps!

**Comment by haesleinhuepf** [comment]
Hey @tischi 

did this help? Can I close that issue?

Btw. usage-questions are better discussed on image.sc ;-)
