### ISSUE TITLE
Image names

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#54]
I worked on an image and wanted to do an auto-threshold with the Assistant.
The I changed my mind and closed the auto-threshold window.
This left me with non-ideal image names:
```
run("Fluorescent Cells");
selectWindow("CLIJxVirtualStack 2");
selectWindow("CLIJxVirtualStack 3");
close();
selectWindow("temp1617979690626.tif");
selectWindow("CLIJx Image of temp1617979690626.tif");
```

**Comment by tischi** [comment]
I just realized that there always is a `temp5758904503503` addition to the image name.
Could be nice to avoid that if possible.

**Comment by haesleinhuepf** [comment]
Hey @tischi ,

good point! Thanks for reporting :-)
