### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#56]
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/2157566/115021001-adfc5400-9ebb-11eb-9c5a-6c8c260b4fb8.png">

It would be super nice if there was a [ Help ] button that would jump to some explanation of the specific tool (in general).

**Comment by haesleinhuepf** [comment]
Great idea @tischi !

I replaced the rather generic "CLIJ assistant online button by a context-dependent help-button:
![image](https://user-images.githubusercontent.com/12660498/115052629-7226b600-9ede-11eb-89e8-e2aa05389430.png)

![image](https://user-images.githubusercontent.com/12660498/115052756-9b474680-9ede-11eb-834e-1501ec37b2ff.png)

Thanks again for all your feedback. It's appreciated!
