### ISSUE TITLE
Configurable output image names

### ISSUE THREAD

**Issue by tischi** [clij/clijx-assistant#57]
With the current scheme the names of the images become very long.
I would suggest solving this like it is done in CellProfiler where the users can themselves chose the name of the output image. The suggested default name could be the one that you are using currently.

**Comment by haesleinhuepf** [comment]
How would that look like? An additional text field in all dialogs?

**Comment by tischi** [comment]
> An additional text field in all dialogs?

Yes.

**Comment by haesleinhuepf** [comment]
I'm afraid that would harm user-convenience as a lot more dialogs would appear (for all the operations that don't have a dialog currently). Furthermore, dialogs would increase in size, which might be a bad idea. See #58 
I keep this issue open until we find a better way of implementing this.
